version: '3.1'

services:
  development_db:
    container_name: development-db
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: developmentpassword
      POSTGRES_USER: shourav
      POSTGRES_DB: doctor_db

  production_db:
    container_name: production-db
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: shourav
      POSTGRES_PASSWORD: productionpassword
      POSTGRES_DB: doctor_db

